# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: <%= ENV['DATABASE_USERNAME'] %>

  # The password associated with the postgres role (username).
  password: <%= ENV['DATABASE_PASSWORD'] %>

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: <%= ENV['DATABASE_HOST'] %>

  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trainers-hub_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: trainers-hub_test

production:
  <<: *default
  database: trainers-hub_production
